name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web


    -  name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    -  name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
          push: true
          tags: arpithadockerhub/dotnettemplate:latest

    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "herukudevopsapp" #Must be unique in Heroku
          heroku_email: "arpitha.mankhala@capita.co.uk" 
          justlogin: true

    - name: "Login to heroku registry"
      run: heroku container:login

    - name: "Build and push to heroku registry"
      run: heroku container:push web --app herukudevopsapp

    - name: "Releases the container"
      run: heroku container:release web --app herukudevopsapp


      # heroku container:push web --app herukudevopsapp
      # heroku container:release web --app herukudevopsapp
      # heroku logs --tail --app herukudevopsapp
      # docker tag arpithadockerhub/dotnettemplate  registry.heroku.com/herukudevopsapp/web